### PR TITLE
Populate Google POI data in graph database

### LINKED ISSUE #29: Google-POI: Populate Google POI data in the graph database
- [x] Extend Graph model
- [x] Setup scraping pipeline based on OSM data
- [x] Save results in Parquet format
- [x] Populate graph
- [x] Dockerize scraping process (run API and scraping script)

### PR DESCRIPTION
**Pull request by mattigrthr**
Closes #29

### CODE REVIEW

**Comment by mattigrthr** [comment]
@bob-bn I had a look at the Dockerization, but I think we should go over it in a pair-programming session. Because the scraping API needs to be running and then we can run the scraping script that generates the search strings and queries the API. I don't know what the best practice is here. I read some stuff about `supervisors,` but I'm not sure whether this is the right way.

**Comment by mattigrthr** [comment]
@bob-bn I finished the Dockerization and tested everything. The scraper is a separate profile and then the scraping pipeline can be run as a service (see README).

**Review by bob-bn — DISMISSED** [review]

**Comment by mattigrthr** [comment]
This is ready to merge now.

**Review by bob-bn — APPROVED** [review]

**Comment by bob-bn** [comment]
Good job @mattigrthr !

**Pull request merged**
